-- Nectar catalog import generated from https://perfumenectar.com/shop
-- Source catalog: 401 unique perfumes (159 women, 169 men, 73 unisex)
-- Safe to run more than once: existing brands, perfumes, and size links are reused.

begin;

create temporary table nectar_import_brands (
  name text primary key
) on commit preserve rows;

insert into nectar_import_brands (name) values
  ('Afnan'),
  ('Ajmal'),
  ('Amouage'),
  ('Antonio Banderas'),
  ('Aramis'),
  ('Ard Al Zaafaran'),
  ('Avon'),
  ('Azzaro'),
  ('Britney Spears'),
  ('Burberry'),
  ('Bvlgari'),
  ('Cacharel'),
  ('Calvin Klein'),
  ('Carolina Herrera'),
  ('Caron'),
  ('Cartier'),
  ('Chanel''s'),
  ('Chopard'),
  ('Christian Dior''s'),
  ('Creed''s'),
  ('Davidoff'),
  ('Diesel'),
  ('Dolce & Gabbana'),
  ('Dunhill'),
  ('Elie Saab'),
  ('Ermenegildo Zegna'),
  ('Escada'),
  ('Estée Lauder'),
  ('Ferrari'),
  ('Giorgio Armani'),
  ('Gissah'),
  ('Givenchy'),
  ('Gucci'),
  ('Guerlain'),
  ('Guy Laroche'),
  ('Hermès'),
  ('Hugo Boss'),
  ('Hummer'),
  ('Issey Miyake'),
  ('Jacques Bogart'),
  ('Jaguar'),
  ('Jean Paul Gaultier'),
  ('Jo Malone London'),
  ('Joop!'),
  ('Kayali'),
  ('Kenzo'),
  ('Kilian'),
  ('Lacoste'),
  ('Lalique'),
  ('Lancôme'),
  ('Lanvin'),
  ('Lattafa'),
  ('Laura Biagiotti'),
  ('Le Labo'),
  ('Lexus'),
  ('LV''s'),
  ('Maison Francis Kurkdjian'),
  ('Mancera'),
  ('Matière Première'),
  ('Mäurer & Wirtz'),
  ('Michael Jordan'),
  ('Montale'),
  ('Montblanc'),
  ('Mugler'),
  ('Narciso Rodriguez'),
  ('Nasomatto'),
  ('Nautica'),
  ('Nectar'),
  ('Nikos'),
  ('Nina Ricci'),
  ('Orto Parisi'),
  ('Paco Rabanne'),
  ('Parfums de Marly'),
  ('Paris Hilton'),
  ('Prada'),
  ('Ralph Lauren'),
  ('Rasasi'),
  ('Reyane Tradition'),
  ('Roberto Cavalli'),
  ('S.T. Dupont'),
  ('Swiss Arabian'),
  ('Ted Lapidus'),
  ('Tom Ford''s'),
  ('Valentino'),
  ('Versace'),
  ('Victoria''s Secret'),
  ('Viktor&Rolf'),
  ('Xerjoff'),
  ('Yves Saint Laurent');

-- Build this staging table from the real column types, including the sex enum
-- if your schema uses one.
create temporary table nectar_import_perfumes
on commit preserve rows
as
select
  perfume.name,
  perfume.name as match_name,
  brand.name as brand_name,
  perfume.sex
from public.perfumes perfume
cross join public.brands brand
with no data;

insert into nectar_import_perfumes (name, match_name, brand_name, sex) values
  ('SUNSET NECTAR', 'SUNSET NECTAR', 'Nectar', 'unisex'),
  ('ACQUA DI GIOIA', 'ACQUA DI GIOIA', 'Giorgio Armani', 'women'),
  ('ANGE ÉTRANGE', 'ANGE ÉTRANGE', 'Givenchy', 'women'),
  ('ANGEL', 'ANGEL', 'Mugler', 'women'),
  ('ANGEL ELIXIR', 'ANGEL ELIXIR', 'Mugler', 'women'),
  ('ALIEN', 'ALIEN', 'Mugler', 'women'),
  ('ALIEN OUD', 'ALIEN OUD', 'Mugler', 'women'),
  ('ARMANI CODE', 'ARMANI CODE', 'Giorgio Armani', 'women'),
  ('ARMANI CODE CASHMERE', 'ARMANI CODE CASHMERE', 'Giorgio Armani', 'women'),
  ('AZZARO MADEMOISELLE', 'MADEMOISELLE', 'Azzaro', 'women'),
  ('BRITNEY SPEARS', 'BRITNEY SPEARS', 'Britney Spears', 'women'),
  ('BURBERRY', 'BURBERRY', 'Burberry', 'women'),
  ('BURBERRY HER', 'HER', 'Burberry', 'women'),
  ('BURBERRY GODDESS', 'GODDESS', 'Burberry', 'women'),
  ('BURBERRY BODY', 'BODY', 'Burberry', 'women'),
  ('BURBERRY ELIXIR', 'ELIXIR', 'Burberry', 'women'),
  ('BECAUSE IT''S YOU', 'BECAUSE IT''S YOU', 'Giorgio Armani', 'women'),
  ('BRIGHT CRYSTAL', 'BRIGHT CRYSTAL', 'Versace', 'women'),
  ('BLACK OPIUM', 'BLACK OPIUM', 'Yves Saint Laurent', 'women'),
  ('BOMB SHELL', 'BOMB SHELL', 'Victoria''s Secret', 'women'),
  ('BOMB FLOWER', 'BOMB FLOWER', 'Viktor&Rolf', 'women'),
  ('BVLGARI OMNIA', 'OMNIA', 'Bvlgari', 'women'),
  ('BLACK XS', 'BLACK XS', 'Paco Rabanne', 'women'),
  ('CHANEL CHANCE', 'CHANCE', 'Chanel''s', 'women'),
  ('CHANCE EAU TENDRE', 'CHANCE EAU TENDRE', 'Chanel''s', 'women'),
  ('CHANEL ALLURE', 'ALLURE', 'Chanel''s', 'women'),
  ('CHANEL NO 5', 'NO 5', 'Chanel''s', 'women'),
  ('CHANEL EAU VIVE', 'EAU VIVE', 'Chanel''s', 'women'),
  ('COCO MADEMOISELLE', 'COCO MADEMOISELLE', 'Chanel''s', 'women'),
  ('COCO CHANEL NOIR', 'COCO CHANEL NOIR', 'Chanel''s', 'women'),
  ('COOL WATER DAVIDOFF', 'COOL WATER DAVIDOFF', 'Davidoff', 'women'),
  ('CRYSTAL NOIR', 'CRYSTAL NOIR', 'Versace', 'women'),
  ('CRAZY IN LOVE', 'CRAZY IN LOVE', 'Nectar', 'women'),
  ('CAROLINA HERRERA', 'CAROLINA HERRERA', 'Carolina Herrera', 'women'),
  ('CREED ROYAL', 'ROYAL', 'Creed''s', 'women'),
  ('CANDY PRADA', 'CANDY PRADA', 'Prada', 'women'),
  ('DIOR ADDICT', 'ADDICT', 'Christian Dior''s', 'women'),
  ('DOLCE&GABBANA', 'DOLCE&GABBANA', 'Dolce & Gabbana', 'women'),
  ('DELINA EXCLUSIF', 'DELINA EXCLUSIF', 'Parfums de Marly', 'women'),
  ('DEVOTION', 'DEVOTION', 'Dolce & Gabbana', 'women'),
  ('EUPHORIA', 'EUPHORIA', 'Calvin Klein', 'women'),
  ('ESCADA TAJ', 'TAJ', 'Escada', 'women'),
  ('ESCADA COLLECTION', 'COLLECTION', 'Escada', 'women'),
  ('ESCADA MAGNETISM', 'MAGNETISM', 'Escada', 'women'),
  ('ESCADA CHERRY', 'CHERRY', 'Escada', 'women'),
  ('ESCADA MOON SPARKLE', 'MOON SPARKLE', 'Escada', 'women'),
  ('ESCADA FLOR DEL SOL', 'FLOR DEL SOL', 'Escada', 'women'),
  ('ELIE SAAB GIRL OF NOW', 'GIRL OF NOW', 'Elie Saab', 'women'),
  ('ELIE SAAB', 'ELIE SAAB', 'Elie Saab', 'women'),
  ('ELIE SAAB NOIR', 'NOIR', 'Elie Saab', 'women'),
  ('FAME', 'FAME', 'Paco Rabanne', 'women'),
  ('FAR AWAY', 'FAR AWAY', 'Avon', 'women'),
  ('GUCCI BLOOM', 'BLOOM', 'Gucci', 'women'),
  ('GUCCI GUILTY', 'GUILTY', 'Gucci', 'women'),
  ('GUCCI RUSH', 'RUSH', 'Gucci', 'women'),
  ('GUCCI BAMBOO', 'BAMBOO', 'Gucci', 'women'),
  ('GUCCI FLORA GORGEOUS ORCHID', 'FLORA GORGEOUS ORCHID', 'Gucci', 'women'),
  ('GUCCI FLORA GORGEOUS MAGNOLIA', 'FLORA GORGEOUS MAGNOLIA', 'Gucci', 'women'),
  ('GOOD GIRL', 'GOOD GIRL', 'Carolina Herrera', 'women'),
  ('GOOD GIRL BUSH', 'GOOD GIRL BUSH', 'Carolina Herrera', 'women'),
  ('GOOD GIRL VERY GLAM', 'GOOD GIRL VERY GLAM', 'Carolina Herrera', 'women'),
  ('GIVENCHY IRRESISTIBLE', 'IRRESISTIBLE', 'Givenchy', 'women'),
  ('GEORGINA''S SENSE', 'GEORGINA''S SENSE', 'Nectar', 'women'),
  ('HUGO BOSS', 'HUGO BOSS', 'Hugo Boss', 'women'),
  ('HYPNOSE', 'HYPNOSE', 'Lancôme', 'women'),
  ('HYPNOTIC POISON', 'HYPNOTIC POISON', 'Christian Dior''s', 'women'),
  ('HAWAI', 'HAWAI', 'Nectar', 'women'),
  ('IDÔLE', 'IDÔLE', 'Lancôme', 'women'),
  ('INSOLENCE', 'INSOLENCE', 'Guerlain', 'women'),
  ('ICELAND', 'ICELAND', 'Nectar', 'women'),
  ('ISSEY MIYAKE', 'ISSEY MIYAKE', 'Issey Miyake', 'women'),
  ('J''ADORE', 'J''ADORE', 'Christian Dior''s', 'women'),
  ('JOY', 'JOY', 'Christian Dior''s', 'women'),
  ('KENZO FLOWER', 'FLOWER', 'Kenzo', 'women'),
  ('KAYALI VANILLA 28', 'VANILLA 28', 'Kayali', 'women'),
  ('KAYALI SWEET BANANA', 'SWEET BANANA', 'Kayali', 'women'),
  ('KAYALI VANILLA OUD', 'VANILLA OUD', 'Kayali', 'women'),
  ('KAYALI MARSHMALLOW', 'MARSHMALLOW', 'Kayali', 'women'),
  ('KAYALI FLOWER MUSC ROSE ROYAL', 'FLOWER MUSC ROSE ROYAL', 'Kayali', 'women'),
  ('KAYALI PISTACHIO', 'PISTACHIO', 'Kayali', 'women'),
  ('LIBRE', 'LIBRE', 'Yves Saint Laurent', 'women'),
  ('LIBRE FLOWERS', 'LIBRE FLOWERS', 'Yves Saint Laurent', 'women'),
  ('LIBRE INTENSE', 'LIBRE INTENSE', 'Yves Saint Laurent', 'women'),
  ('L''INSTANT DE GUERLAIN', 'L''INSTANT DE GUERLAIN', 'Guerlain', 'women'),
  ('LA PETITE ROBE', 'LA PETITE ROBE', 'Guerlain', 'women'),
  ('LA NUIT TRÉSOR', 'LA NUIT TRÉSOR', 'Lancôme', 'women'),
  ('LIGHT BLUE', 'LIGHT BLUE', 'Dolce & Gabbana', 'women'),
  ('LACOSTE TOUCH OF PINK', 'TOUCH OF PINK', 'Lacoste', 'women'),
  ('LADY MILLION', 'LADY MILLION', 'Paco Rabanne', 'women'),
  ('LE BOUQUET ABSOLU', 'LE BOUQUET ABSOLU', 'Yves Saint Laurent', 'women'),
  ('L''INTERDIT GIVENCHY', 'L''INTERDIT GIVENCHY', 'Givenchy', 'women'),
  ('L''INTERDIT ROUGE', 'L''INTERDIT ROUGE', 'Givenchy', 'women'),
  ('LA VIE EST BELLE', 'LA VIE EST BELLE', 'Lancôme', 'women'),
  ('LA BELLE JPG', 'LA BELLE JPG', 'Jean Paul Gaultier', 'women'),
  ('L''EAU D''ISSEY', 'L''EAU D''ISSEY', 'Issey Miyake', 'women'),
  ('LOVE ME MORE', 'LOVE ME MORE', 'Victoria''s Secret', 'women'),
  ('LOVER DOSE', 'LOVER DOSE', 'Diesel', 'women'),
  ('LOVE DELIGHT AMOUAGE', 'LOVE DELIGHT AMOUAGE', 'Amouage', 'women'),
  ('MIDNIGHT FANTASY', 'MIDNIGHT FANTASY', 'Britney Spears', 'women'),
  ('MISS DIOR', 'MISS DIOR', 'Christian Dior''s', 'women'),
  ('MISS DIOR BLOOMING BOUQUET', 'MISS DIOR BLOOMING BOUQUET', 'Christian Dior''s', 'women'),
  ('MY WAY', 'MY WAY', 'Giorgio Armani', 'women'),
  ('MON PARIS', 'MON PARIS', 'Yves Saint Laurent', 'women'),
  ('MONTALE ROSE MUSK', 'ROSE MUSK', 'Montale', 'women'),
  ('MONT BLANC FEMME INDIVIDUELLE', 'MONT BLANC FEMME INDIVIDUELLE', 'Montblanc', 'women'),
  ('MONT BLANC LADY EMBLEM', 'MONT BLANC LADY EMBLEM', 'Montblanc', 'women'),
  ('MONT BLANC SIGNATURE', 'MONT BLANC SIGNATURE', 'Montblanc', 'women'),
  ('MANIFESTO', 'MANIFESTO', 'Yves Saint Laurent', 'women'),
  ('MON GUERLAIN', 'MON GUERLAIN', 'Guerlain', 'women'),
  ('NARCISO BLACK', 'NARCISO BLACK', 'Narciso Rodriguez', 'women'),
  ('NARCISO PINK', 'NARCISO PINK', 'Narciso Rodriguez', 'women'),
  ('NARCISO JASMINE MUSC', 'NARCISO JASMINE MUSC', 'Narciso Rodriguez', 'women'),
  ('NARCISO FLOWER MUSC', 'NARCISO FLOWER MUSC', 'Narciso Rodriguez', 'women'),
  ('NARCISO ROSE MUSC', 'NARCISO ROSE MUSC', 'Narciso Rodriguez', 'women'),
  ('NARCISO MUSC ROSE NOIR', 'NARCISO MUSC ROSE NOIR', 'Narciso Rodriguez', 'women'),
  ('NARCISO POUDRE', 'NARCISO POUDRE', 'Narciso Rodriguez', 'women'),
  ('OLYMPÉA', 'OLYMPÉA', 'Paco Rabanne', 'women'),
  ('PURE POISON', 'PURE POISON', 'Christian Dior''s', 'women'),
  ('PARIS HILTON', 'PARIS HILTON', 'Paris Hilton', 'women'),
  ('PURE XS', 'PURE XS', 'Paco Rabanne', 'women'),
  ('POÊME', 'POÊME', 'Lancôme', 'women'),
  ('PREMIER JOUR', 'PREMIER JOUR', 'Nina Ricci', 'women'),
  ('PRADA PARADOXE', 'PARADOXE', 'Prada', 'women'),
  ('Q D&G', 'Q D&G', 'Dolce & Gabbana', 'women'),
  ('RICCI RICCI', 'RICCI RICCI', 'Nina Ricci', 'women'),
  ('ROBERTO CAVALLI', 'ROBERTO CAVALLI', 'Roberto Cavalli', 'women'),
  ('ROBERTO CAVALLI PARADISE', 'PARADISE', 'Roberto Cavalli', 'women'),
  ('RALPH', 'RALPH', 'Ralph Lauren', 'women'),
  ('SAMSARA GUERLAIN', 'SAMSARA GUERLAIN', 'Guerlain', 'women'),
  ('SUPREME BOUQUET', 'SUPREME BOUQUET', 'Yves Saint Laurent', 'women'),
  ('SI', 'SI', 'Giorgio Armani', 'women'),
  ('SI INTENSE', 'SI INTENSE', 'Giorgio Armani', 'women'),
  ('SI PASSIONE', 'SI PASSIONE', 'Giorgio Armani', 'women'),
  ('SI PASSIONE INTENSE', 'SI PASSIONE INTENSE', 'Giorgio Armani', 'women'),
  ('SCANDAL', 'SCANDAL', 'Jean Paul Gaultier', 'women'),
  ('SEXY GRAFITTI', 'SEXY GRAFITTI', 'Escada', 'women'),
  ('SAHARA NOIR T.F.', 'SAHARA NOIR T.F.', 'Tom Ford''s', 'women'),
  ('TOSCA', 'TOSCA', 'Mäurer & Wirtz', 'women'),
  ('TWILLY D''HERMES', 'TWILLY D''HERMES', 'Hermès', 'women'),
  ('THE ONE', 'THE ONE', 'Dolce & Gabbana', 'women'),
  ('TRESOR', 'TRESOR', 'Lancôme', 'women'),
  ('TRESOR MIDNIGHT ROSE', 'TRESOR MIDNIGHT ROSE', 'Lancôme', 'women'),
  ('TODAY', 'TODAY', 'Avon', 'women'),
  ('TOM FORD METALLIQUE', 'METALLIQUE', 'Tom Ford''s', 'women'),
  ('TOM FORD ORCHID SOLEIL', 'ORCHID SOLEIL', 'Tom Ford''s', 'women'),
  ('TOM FORD SOLEIL BRULANT', 'SOLEIL BRULANT', 'Tom Ford''s', 'women'),
  ('VALENTINO BORN IN ROMA INTENSE', 'BORN IN ROMA INTENSE', 'Valentino', 'women'),
  ('VERSACE DYLAN PURPLE', 'DYLAN PURPLE', 'Versace', 'women'),
  ('VERSACE DYLAN BLUE', 'DYLAN BLUE', 'Versace', 'women'),
  ('VERSACE EROS', 'EROS', 'Versace', 'women'),
  ('VERY SEXY NOW', 'VERY SEXY NOW', 'Victoria''s Secret', 'women'),
  ('VERY IRRESISTIBLE', 'VERY IRRESISTIBLE', 'Givenchy', 'women'),
  ('WASHWASHA BY LATTAFA', 'WASHWASHA BY LATTAFA', 'Lattafa', 'women'),
  ('YARA MOI', 'YARA MOI', 'Lattafa', 'women'),
  ('YARA PINK', 'YARA PINK', 'Lattafa', 'women'),
  ('212', '212', 'Carolina Herrera', 'women'),
  ('212 SEXY', '212 SEXY', 'Carolina Herrera', 'women'),
  ('212 VIP', '212 VIP', 'Carolina Herrera', 'women'),
  ('212 VIP ROSE', '212 VIP ROSE', 'Carolina Herrera', 'women'),
  ('حريم السلطان', 'حريم السلطان', 'Nectar', 'women'),
  ('ACQUA DI GIO', 'ACQUA DI GIO', 'Giorgio Armani', 'men'),
  ('ACQUA DI GIO PROFUMO', 'ACQUA DI GIO PROFUMO', 'Giorgio Armani', 'men'),
  ('ACQUA DI GIO PROFONDO', 'ACQUA DI GIO PROFONDO', 'Giorgio Armani', 'men'),
  ('ACQUA DI GIO ABSOLU', 'ACQUA DI GIO ABSOLU', 'Giorgio Armani', 'men'),
  ('ACQUA DI GIO EXTRA', 'ACQUA DI GIO EXTRA', 'Giorgio Armani', 'men'),
  ('ACQUA DI SILVA', 'ACQUA DI SILVA', 'Nectar', 'men'),
  ('ARMANI CODE ICE', 'ARMANI CODE ICE', 'Giorgio Armani', 'men'),
  ('ALLURE CHANEL', 'ALLURE CHANEL', 'Chanel''s', 'men'),
  ('ALLURE SPORT CHANEL', 'ALLURE SPORT CHANEL', 'Chanel''s', 'men'),
  ('AMBER PRADA', 'AMBER PRADA', 'Prada', 'men'),
  ('AZZARO CHROME', 'CHROME', 'Azzaro', 'men'),
  ('AZZARO WANTED', 'WANTED', 'Azzaro', 'men'),
  ('AZZARO CHROME UNITED', 'CHROME UNITED', 'Azzaro', 'men'),
  ('ARAMIS 900', '900', 'Aramis', 'men'),
  ('ASAD BOURBON', 'ASAD BOURBON', 'Lattafa', 'men'),
  ('BLEU DE CHANEL', 'BLEU DE CHANEL', 'Chanel''s', 'men'),
  ('BOSS BOTTLED', 'BOSS BOTTLED', 'Hugo Boss', 'men'),
  ('BOSS BOTTLED ELIXIR', 'BOSS BOTTLED ELIXIR', 'Hugo Boss', 'men'),
  ('BOSS BOTTLED INTENSE', 'BOSS BOTTLED INTENSE', 'Hugo Boss', 'men'),
  ('BOSS BOTTLED OUD', 'BOSS BOTTLED OUD', 'Hugo Boss', 'men'),
  ('BOSS BOTTLED ABSOLU', 'BOSS BOTTLED ABSOLU', 'Hugo Boss', 'men'),
  ('BOSS THE SCENT', 'BOSS THE SCENT', 'Hugo Boss', 'men'),
  ('BOSS THE SCENT ELIXIR', 'BOSS THE SCENT ELIXIR', 'Hugo Boss', 'men'),
  ('BOSS ORANGE', 'BOSS ORANGE', 'Hugo Boss', 'men'),
  ('BLACK XS L''APHRODISIAQUE', 'BLACK XS L''APHRODISIAQUE', 'Paco Rabanne', 'men'),
  ('BURBERRY HERO', 'HERO', 'Burberry', 'men'),
  ('BVLGARI BLUE', 'BLUE', 'Bvlgari', 'men'),
  ('BVLGARI MEN', 'MEN', 'Bvlgari', 'men'),
  ('BVLGARI MAN IN BLACK', 'MAN IN BLACK', 'Bvlgari', 'men'),
  ('BVLGARI WOOD ESSENCE', 'WOOD ESSENCE', 'Bvlgari', 'men'),
  ('BLUE JEANS', 'BLUE JEANS', 'Versace', 'men'),
  ('BLUE LABEL', 'BLUE LABEL', 'Givenchy', 'men'),
  ('CKI', 'CKI', 'Calvin Klein', 'men'),
  ('CK SHOCK', 'CK SHOCK', 'Calvin Klein', 'men'),
  ('CREED AVENTUS', 'AVENTUS', 'Creed''s', 'men'),
  ('CREED SILVER MOUNTAIN', 'SILVER MOUNTAIN', 'Creed''s', 'men'),
  ('CREED AVENTUS ABSOLU', 'AVENTUS ABSOLU', 'Creed''s', 'men'),
  ('CAROLINA HERRERA CLASSIC', 'CLASSIC', 'Carolina Herrera', 'men'),
  ('CAROLINA HERRERA CHIC', 'CHIC', 'Carolina Herrera', 'men'),
  ('CARLISLE DE MARLY', 'CARLISLE DE MARLY', 'Parfums de Marly', 'men'),
  ('CHOPARD OUD MALAKI', 'OUD MALAKI', 'Chopard', 'men'),
  ('CARTIER DECLARATION', 'DECLARATION', 'Cartier', 'men'),
  ('CACHAREL', 'CACHAREL', 'Cacharel', 'men'),
  ('DAVIDOFF HOT WATER', 'HOT WATER', 'Davidoff', 'men'),
  ('DAVIDOFF COOL WATER', 'COOL WATER', 'Davidoff', 'men'),
  ('DAVIDOFF ADVENTURE', 'ADVENTURE', 'Davidoff', 'men'),
  ('DAVIDOFF CHAMPION', 'CHAMPION', 'Davidoff', 'men'),
  ('DIOR HOMME', 'HOMME', 'Christian Dior''s', 'men'),
  ('DIOR HOMME SPORT', 'HOMME SPORT', 'Christian Dior''s', 'men'),
  ('DIOR INTENSE', 'INTENSE', 'Christian Dior''s', 'men'),
  ('DIOR HIGHER', 'HIGHER', 'Christian Dior''s', 'men'),
  ('D&G LIGHT BLUE', 'D&G LIGHT BLUE', 'Dolce & Gabbana', 'men'),
  ('D&G K', 'D&G K', 'Dolce & Gabbana', 'men'),
  ('DYLAN BLUE', 'DYLAN BLUE', 'Versace', 'men'),
  ('DRAKKAR NOIR', 'DRAKKAR NOIR', 'Guy Laroche', 'men'),
  ('DUNHILL ICON', 'ICON', 'Dunhill', 'men'),
  ('DUNHILL DARK BLUE', 'DARK BLUE', 'Dunhill', 'men'),
  ('DUNHILL DESIRE', 'DESIRE', 'Dunhill', 'men'),
  ('DUNHILL DESIRE BLUE', 'DESIRE BLUE', 'Dunhill', 'men'),
  ('EAU SAUVAGE', 'EAU SAUVAGE', 'Christian Dior''s', 'men'),
  ('EROS FLAME', 'EROS FLAME', 'Versace', 'men'),
  ('EHSAAS', 'EHSAAS', 'Lattafa', 'men'),
  ('ENCRE NOIR', 'ENCRE NOIR', 'Lalique', 'men'),
  ('ETERNITY', 'ETERNITY', 'Calvin Klein', 'men'),
  ('EGOISTE PLATINUM', 'EGOISTE PLATINUM', 'Chanel''s', 'men'),
  ('FAHRENHEIT', 'FAHRENHEIT', 'Christian Dior''s', 'men'),
  ('FERRARI RED', 'RED', 'Ferrari', 'men'),
  ('GIVENCHY PLAY', 'PLAY', 'Givenchy', 'men'),
  ('GIVENCHY PLAY SPORT', 'PLAY SPORT', 'Givenchy', 'men'),
  ('GIVENCHY GENTLEMAN', 'GENTLEMAN', 'Givenchy', 'men'),
  ('GIVENCHY PI', 'PI', 'Givenchy', 'men'),
  ('HUMMER', 'HUMMER', 'Hummer', 'men'),
  ('HABIT ROUGE', 'HABIT ROUGE', 'Guerlain', 'men'),
  ('HUGO BOSS ENERGIZE', 'ENERGIZE', 'Hugo Boss', 'men'),
  ('H 24', 'H 24', 'Hermès', 'men'),
  ('INVICTUS', 'INVICTUS', 'Paco Rabanne', 'men'),
  ('INVICTUS VICTORY', 'INVICTUS VICTORY', 'Paco Rabanne', 'men'),
  ('INVICTUS PLATINUM', 'INVICTUS PLATINUM', 'Paco Rabanne', 'men'),
  ('INVICTUS PARFUM', 'INVICTUS PARFUM', 'Paco Rabanne', 'men'),
  ('INVICTUS VICTORY ELIXIR', 'INVICTUS VICTORY ELIXIR', 'Paco Rabanne', 'men'),
  ('INSURRECTION', 'INSURRECTION', 'Reyane Tradition', 'men'),
  ('JOOP', 'JOOP', 'Joop!', 'men'),
  ('JAGUAR', 'JAGUAR', 'Jaguar', 'men'),
  ('JAVANESE PATCHOULI', 'JAVANESE PATCHOULI', 'Ermenegildo Zegna', 'men'),
  ('KENZO', 'KENZO', 'Kenzo', 'men'),
  ('KOUROS', 'KOUROS', 'Yves Saint Laurent', 'men'),
  ('LE MALE', 'LE MALE', 'Jean Paul Gaultier', 'men'),
  ('LE MALE ELIXIR', 'LE MALE ELIXIR', 'Jean Paul Gaultier', 'men'),
  ('LE MALE LE BEAU', 'LE MALE LE BEAU', 'Jean Paul Gaultier', 'men'),
  ('LE MALE LOVER', 'LE MALE LOVER', 'Jean Paul Gaultier', 'men'),
  ('LE MALE LE PARFUM', 'LE MALE LE PARFUM', 'Jean Paul Gaultier', 'men'),
  ('L''IMMENSITÉ LV', 'L''IMMENSITÉ LV', 'LV''s', 'men'),
  ('LACOSTE WHITE', 'WHITE', 'Lacoste', 'men'),
  ('LACOSTE RED', 'RED', 'Lacoste', 'men'),
  ('LACOSTE POUR L''HOMME', 'POUR L''HOMME', 'Lacoste', 'men'),
  ('LAYTON DE MARLY', 'LAYTON DE MARLY', 'Parfums de Marly', 'men'),
  ('LA NUIT DE L''HOMME', 'LA NUIT DE L''HOMME', 'Yves Saint Laurent', 'men'),
  ('LEXUS', 'LEXUS', 'Lexus', 'men'),
  ('LANVIN', 'LANVIN', 'Lanvin', 'men'),
  ('LAPIDUS', 'LAPIDUS', 'Ted Lapidus', 'men'),
  ('LAIL MALAKI', 'LAIL MALAKI', 'Swiss Arabian', 'men'),
  ('MONT BLANC LEGEND', 'MONT BLANC LEGEND', 'Montblanc', 'men'),
  ('MONT BLANC LEGEND RED', 'MONT BLANC LEGEND RED', 'Montblanc', 'men'),
  ('MONT BLANC LEGEND SPIRIT', 'MONT BLANC LEGEND SPIRIT', 'Montblanc', 'men'),
  ('MONT BLANC EXPLORER', 'MONT BLANC EXPLORER', 'Montblanc', 'men'),
  ('MONT BLANC INDIVIDUELLE', 'MONT BLANC INDIVIDUELLE', 'Montblanc', 'men'),
  ('MYSELF YSL', 'MYSELF YSL', 'Yves Saint Laurent', 'men'),
  ('MR BURBERRY', 'MR BURBERRY', 'Burberry', 'men'),
  ('NAUTICA VOYAGE', 'VOYAGE', 'Nautica', 'men'),
  ('NARCISO BLEU NOIR', 'NARCISO BLEU NOIR', 'Narciso Rodriguez', 'men'),
  ('M.J. WEEKEND', 'M.J. WEEKEND', 'Michael Jordan', 'men'),
  ('OMBRE LEATHER', 'OMBRE LEATHER', 'Tom Ford''s', 'men'),
  ('OMBRE NOMADE LV', 'OMBRE NOMADE LV', 'LV''s', 'men'),
  ('ONE MILLION', 'ONE MILLION', 'Paco Rabanne', 'men'),
  ('ONE MILLION OUD', 'ONE MILLION OUD', 'Paco Rabanne', 'men'),
  ('ONE MILLION LUCKY', 'ONE MILLION LUCKY', 'Paco Rabanne', 'men'),
  ('ONE MILLION ELIXIR', 'ONE MILLION ELIXIR', 'Paco Rabanne', 'men'),
  ('POLO RED', 'POLO RED', 'Ralph Lauren', 'men'),
  ('POLO BLACK', 'POLO BLACK', 'Ralph Lauren', 'men'),
  ('POLO BLUE', 'POLO BLUE', 'Ralph Lauren', 'men'),
  ('PACO RABANNE PHANTOM', 'PHANTOM', 'Paco Rabanne', 'men'),
  ('PACO RABANNE MEN', 'MEN', 'Paco Rabanne', 'men'),
  ('PRADA L''HOMME', 'L''HOMME', 'Prada', 'men'),
  ('PARFUMS DE MARLY ALTHAÏR', 'ALTHAÏR', 'Parfums de Marly', 'men'),
  ('PASHA DE CARTIER', 'PASHA DE CARTIER', 'Cartier', 'men'),
  ('PLEASURES', 'PLEASURES', 'Calvin Klein', 'men'),
  ('RED TABACCO MANCERA', 'RED TABACCO MANCERA', 'Mancera', 'men'),
  ('ROMA', 'ROMA', 'Laura Biagiotti', 'men'),
  ('RASASI HAWAS', 'HAWAS', 'Rasasi', 'men'),
  ('RASASI AL WISAM', 'AL WISAM', 'Rasasi', 'men'),
  ('SAUVAGE', 'SAUVAGE', 'Christian Dior''s', 'men'),
  ('SAUVAGE ELIXIR', 'SAUVAGE ELIXIR', 'Christian Dior''s', 'men'),
  ('STRONGER WITH YOU', 'STRONGER WITH YOU', 'Giorgio Armani', 'men'),
  ('STRONGER WITH YOU INTENSELY', 'STRONGER WITH YOU INTENSELY', 'Giorgio Armani', 'men'),
  ('SWY ABSOLUTELY', 'SWY ABSOLUTELY', 'Giorgio Armani', 'men'),
  ('SWY OUD', 'SWY OUD', 'Giorgio Armani', 'men'),
  ('SWY PARFUM', 'SWY PARFUM', 'Giorgio Armani', 'men'),
  ('STRONG ME', 'STRONG ME', 'Paco Rabanne', 'men'),
  ('SILVER SCENT', 'SILVER SCENT', 'Jacques Bogart', 'men'),
  ('SCANDAL POUR HOMME', 'SCANDAL POUR HOMME', 'Jean Paul Gaultier', 'men'),
  ('SHADOWS', 'SHADOWS', 'Ajmal', 'men'),
  ('SEDUCTION BLACK', 'SEDUCTION BLACK', 'Antonio Banderas', 'men'),
  ('SPICE BOMB EXTREME', 'SPICE BOMB EXTREME', 'Viktor&Rolf', 'men'),
  ('SPICE BOMB', 'SPICE BOMB', 'Viktor&Rolf', 'men'),
  ('SPICE BOMB INFRARED', 'SPICE BOMB INFRARED', 'Viktor&Rolf', 'men'),
  ('SCULPTURE HOMME', 'SCULPTURE HOMME', 'Nikos', 'men'),
  ('TABAC', 'TABAC', 'Mäurer & Wirtz', 'men'),
  ('TOBACCO VANILLE', 'TOBACCO VANILLE', 'Tom Ford''s', 'men'),
  ('THE MOST WANTED', 'THE MOST WANTED', 'Azzaro', 'men'),
  ('TOM FORD NOIR DE NOIR', 'NOIR DE NOIR', 'Tom Ford''s', 'men'),
  ('TOM FORD OUD WOOD', 'OUD WOOD', 'Tom Ford''s', 'men'),
  ('TOM FORD NOIR EXTREME', 'NOIR EXTREME', 'Tom Ford''s', 'men'),
  ('TERRE D''HERMES', 'TERRE D''HERMES', 'Hermès', 'men'),
  ('TUXEDO', 'TUXEDO', 'Yves Saint Laurent', 'men'),
  ('ULTRA MALE', 'ULTRA MALE', 'Jean Paul Gaultier', 'men'),
  ('VÉTIVER DE GUERLAIN', 'VÉTIVER DE GUERLAIN', 'Guerlain', 'men'),
  ('VERSACE POUR HOMME', 'POUR HOMME', 'Versace', 'men'),
  ('VERSACE EAU FRAICHE', 'EAU FRAICHE', 'Versace', 'men'),
  ('VALENTINO UOMO', 'UOMO', 'Valentino', 'men'),
  ('VALENTINO UOMO NOIR ABSOLU', 'UOMO NOIR ABSOLU', 'Valentino', 'men'),
  ('VALENTINO UOMO BORN N ROME', 'UOMO BORN N ROME', 'Valentino', 'men'),
  ('VALENTINO UAMO BORN IN ROME INTENSE', 'UAMO BORN IN ROME INTENSE', 'Valentino', 'men'),
  ('WOOD MYSTIQUE', 'WOOD MYSTIQUE', 'Estée Lauder', 'men'),
  ('Y', 'Y', 'Yves Saint Laurent', 'men'),
  ('Y LE PARFUM', 'Y LE PARFUM', 'Yves Saint Laurent', 'men'),
  ('Y INTENSE', 'Y INTENSE', 'Yves Saint Laurent', 'men'),
  ('212 VIP BLACK', '212 VIP BLACK', 'Carolina Herrera', 'men'),
  ('212 MEN', '212 MEN', 'Carolina Herrera', 'men'),
  ('دارج', 'دارج', 'Nectar', 'men'),
  ('ANA AL ABYAD', 'ANA AL ABYAD', 'Lattafa', 'unisex'),
  ('ANA WEL SHOOQ', 'ANA WEL SHOOQ', 'Nectar', 'unisex'),
  ('AMORE CAFFE MANCERA', 'AMORE CAFFE MANCERA', 'Mancera', 'unisex'),
  ('AMBER SANTAL AJMAL', 'AMBER SANTAL AJMAL', 'Ajmal', 'unisex'),
  ('ARMANI PRIVE ROYAL OUD', 'ARMANI PRIVE ROYAL OUD', 'Giorgio Armani', 'unisex'),
  ('ARMANI PRIVE ROUGE MALACHITE', 'ARMANI PRIVE ROUGE MALACHITE', 'Giorgio Armani', 'unisex'),
  ('ARMANI PRIVE VERT MALACHITE', 'ARMANI PRIVE VERT MALACHITE', 'Giorgio Armani', 'unisex'),
  ('BACCARAT ROUGE', 'BACCARAT ROUGE', 'Maison Francis Kurkdjian', 'unisex'),
  ('BLACK ORCHIDE', 'BLACK ORCHIDE', 'Tom Ford''s', 'unisex'),
  ('BLACK AFGANO', 'BLACK AFGANO', 'Nasomatto', 'unisex'),
  ('BLACK AOUDE MONTALE', 'BLACK AOUDE MONTALE', 'Montale', 'unisex'),
  ('BOIS MYSTERIEUX GUERLAIN', 'BOIS MYSTERIEUX GUERLAIN', 'Guerlain', 'unisex'),
  ('BOIS CORSE', 'BOIS CORSE', 'Matière Première', 'unisex'),
  ('COCO VANILLE', 'COCO VANILLE', 'Mancera', 'unisex'),
  ('CREED ROYAL AOUD', 'ROYAL AOUD', 'Creed''s', 'unisex'),
  ('CREED ROYAL WATER', 'ROYAL WATER', 'Creed''s', 'unisex'),
  ('CARON', 'CARON', 'Caron', 'unisex'),
  ('CAFTAN YSL', 'CAFTAN YSL', 'Yves Saint Laurent', 'unisex'),
  ('CAPRI', 'CAPRI', 'Gissah', 'unisex'),
  ('CALIFORNIA DREAM LV', 'CALIFORNIA DREAM LV', 'LV''s', 'unisex'),
  ('CRYSTAL SAAFFRON MATIERE PREMIERE', 'CRYSTAL SAAFFRON MATIERE PREMIERE', 'Matière Première', 'unisex'),
  ('DIOR GRIS', 'GRIS', 'Christian Dior''s', 'unisex'),
  ('ERBA PURA', 'ERBA PURA', 'Xerjoff', 'unisex'),
  ('GUCCI AOUD', 'AOUD', 'Gucci', 'unisex'),
  ('GUCCI AOUD INTENSE', 'AOUD INTENSE', 'Gucci', 'unisex'),
  ('HUDSON VALLEY', 'HUDSON VALLEY', 'Gissah', 'unisex'),
  ('IMPERIAL VALLEY', 'IMPERIAL VALLEY', 'Gissah', 'unisex'),
  ('JOE MALONE VELVET ROSE AND OUD', 'JOE MALONE VELVET ROSE AND OUD', 'Jo Malone London', 'unisex'),
  ('LE LION DE CHANEL', 'LE LION DE CHANEL', 'Chanel''s', 'unisex'),
  ('LEATHER MALAKI CHOPARD', 'LEATHER MALAKI CHOPARD', 'Chopard', 'unisex'),
  ('MONTALE ARABIANS TONKA', 'ARABIANS TONKA', 'Montale', 'unisex'),
  ('MEGAMARE', 'MEGAMARE', 'Orto Parisi', 'unisex'),
  ('OUD ISPAHAN', 'OUD ISPAHAN', 'Christian Dior''s', 'unisex'),
  ('OUD AND BERGAMOT JO MALONE', 'OUD AND BERGAMOT JO MALONE', 'Jo Malone London', 'unisex'),
  ('OUD ABYAD', 'OUD ABYAD', 'Afnan', 'unisex'),
  ('ROSE VANILLE', 'ROSE VANILLE', 'Montale', 'unisex'),
  ('SANTAL 33', 'SANTAL 33', 'Le Labo', 'unisex'),
  ('SANTAL ROYAL GUERLAIN', 'SANTAL ROYAL GUERLAIN', 'Guerlain', 'unisex'),
  ('SHAMS EL EMARAT', 'SHAMS EL EMARAT', 'Ard Al Zaafaran', 'unisex'),
  ('S.T. DUPONT OUD AND ROSE', 'OUD AND ROSE', 'S.T. Dupont', 'unisex'),
  ('STRONGER WITH YOU AMBER', 'STRONGER WITH YOU AMBER', 'Giorgio Armani', 'unisex'),
  ('STELLAR TIMES LV', 'STELLAR TIMES LV', 'LV''s', 'unisex'),
  ('SMOKING HOT', 'SMOKING HOT', 'Kilian', 'unisex'),
  ('SWY TOBACCO', 'SWY TOBACCO', 'Giorgio Armani', 'unisex'),
  ('SWY SANDALWOOD', 'SWY SANDALWOOD', 'Giorgio Armani', 'unisex'),
  ('SWY LEATHER', 'SWY LEATHER', 'Giorgio Armani', 'unisex'),
  ('TOBACCO OUD', 'TOBACCO OUD', 'Tom Ford''s', 'unisex'),
  ('TERIAQ INTENSE LATTAFA', 'TERIAQ INTENSE LATTAFA', 'Lattafa', 'unisex'),
  ('TOM FORD VANILLA SEX', 'VANILLA SEX', 'Tom Ford''s', 'unisex'),
  ('TOM FORD NEROLI PORTOFINO', 'NEROLI PORTOFINO', 'Tom Ford''s', 'unisex'),
  ('TOM FORD ELECTRIC CHERRY', 'ELECTRIC CHERRY', 'Tom Ford''s', 'unisex'),
  ('TOM FORD LOST CHERRY', 'LOST CHERRY', 'Tom Ford''s', 'unisex'),
  ('TOM FORD BITTER PEACH', 'BITTER PEACH', 'Tom Ford''s', 'unisex'),
  ('TOM FORD CHERRY SMOKE', 'CHERRY SMOKE', 'Tom Ford''s', 'unisex'),
  ('TOM FORD FUCKING FABULOUS', 'FUCKING FABULOUS', 'Tom Ford''s', 'unisex'),
  ('VELVET DESERT OUD D&G', 'VELVET DESERT OUD D&G', 'Dolce & Gabbana', 'unisex'),
  ('VELVT DESERT OUD', 'VELVT DESERT OUD', 'Dolce & Gabbana', 'unisex'),
  ('WITHE OUD', 'WITHE OUD', 'Montale', 'unisex'),
  ('WESAL', 'WESAL', 'Ajmal', 'unisex'),
  ('XERJOFF ALEXANDRIA', 'ALEXANDRIA', 'Xerjoff', 'unisex'),
  ('XERJOFF NAXOS', 'NAXOS', 'Xerjoff', 'unisex'),
  ('XERJOFF DECAS', 'DECAS', 'Xerjoff', 'unisex'),
  ('غبار الذهب', 'غبار الذهب', 'Nectar', 'unisex'),
  ('سفير العود', 'سفير العود', 'Nectar', 'unisex'),
  ('كلمات', 'كلمات', 'Nectar', 'unisex'),
  ('خمرة', 'خمرة', 'Lattafa', 'unisex'),
  ('شيخ الشيوخ', 'شيخ الشيوخ', 'Nectar', 'unisex'),
  ('شغف', 'شغف', 'Nectar', 'unisex'),
  ('عود مبخر', 'عود مبخر', 'Nectar', 'unisex'),
  ('بخور', 'بخور', 'Nectar', 'unisex'),
  ('عود الذهب', 'عود الذهب', 'Nectar', 'unisex'),
  ('دهن العود', 'دهن العود', 'Nectar', 'unisex');

-- Create only brands that are not already present.
insert into public.brands (name, is_active)
select source.name, true
from nectar_import_brands source
where not exists (
  select 1
  from public.brands existing
  where lower(trim(existing.name)) = lower(trim(source.name))
);

-- Create only perfumes that are not already present. match_name handles entries
-- such as CREED AVENTUS when an existing row is named simply Aventus.
insert into public.perfumes (
  name,
  perfume_brand,
  sex,
  image_url,
  is_active,
  is_featured
)
select
  source.name,
  brand.id,
  source.sex,
  null,
  true,
  false
from nectar_import_perfumes source
join public.brands brand
  on lower(trim(brand.name)) = lower(trim(source.brand_name))
where not exists (
  select 1
  from public.perfumes existing
  where lower(trim(existing.name)) in (
    lower(trim(source.name)),
    lower(trim(source.match_name))
  )
);

-- Resolve every imported catalog entry to its database perfume row.
create temporary table nectar_import_ids on commit preserve rows as
select distinct existing.id as perfume_id
from nectar_import_perfumes source
join public.perfumes existing
  on lower(trim(existing.name)) in (
    lower(trim(source.name)),
    lower(trim(source.match_name))
  );

-- Give every imported perfume both required sizes.
insert into public.perfume_size (perfume, size, price)
select imported.perfume_id, requested.size_id, null
from nectar_import_ids imported
cross join (values (1), (2)) as requested(size_id)
where not exists (
  select 1
  from public.perfume_size existing
  where existing.perfume = imported.perfume_id
    and existing.size = requested.size_id
);

commit;

-- Verification: expected catalog_entries = 401 and missing_size_links = 0.
select
  (select count(*) from nectar_import_perfumes) as catalog_entries,
  (select count(*) from nectar_import_perfumes source where exists (
    select 1 from public.perfumes perfume
    where lower(trim(perfume.name)) in (lower(trim(source.name)), lower(trim(source.match_name)))
  )) as matched_catalog_entries,
  (select count(*) from nectar_import_ids imported
    cross join (values (1), (2)) requested(size_id)
    where not exists (
      select 1 from public.perfume_size link
      where link.perfume = imported.perfume_id and link.size = requested.size_id
    )
  ) as missing_size_links;
